#--- ASV Nav2 Params ---#
# 1. bt_navigator
# 2. controller_server
# 3. local_costmap
# 4. global_costmap
# 5. map_server
# 6. planner_server
# 7. behavior_server

asv/bt_navigator:
  ros__parameters:
    use_sim_time: false
    bt_xml_filename: "/opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"
    default_nav_to_pose_bt_xml: "/opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"
    #default_nav_through_poses_bt_xml: "/opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml"
    global_frame: "map"
    robot_base_frame: "asv/base_link"
    # Add these to silence the warning
    follow_path_error_code: 10
    compute_path_error_code: 11
    # Optional error code mapping
    error_code_names:
      - follow_path_error_code
      - compute_path_error_code
      - goal_check_failure_error_code
      - planner_failed_error_code
      - unknown_error_code
    #plugin_lib_names:
      #- nav2_spin_action_bt_node
      #- nav2_compute_path_to_pose_action_bt_node
      #- nav2_follow_path_action_bt_node
      #- nav2_spin_action_bt_node  # <- This one is missing!
      #- nav2_wait_action_bt_node
      #- nav2_back_up_action_bt_node
      #- nav2_clear_costmap_service_bt_node

#--- prediction_horizon_s = steps * dt ---#
#--- prediction_horizon_s * vmax <= local_side/2 otherwise movement will stutter --#
#--- prediction_horizon_s * max_speed / path_resolution / 3.0 = path_offset ---#
asv/controller_server:
  ros__parameters:
    controller_frequency: 20.0
    publish_zero_velocity: True
    costmap_update_timeout: 0.6 # after 3 failed updates timeout
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3      # after fails for 0.3s then fail pathing action


    progress_checker_plugins: [ "progress_checker" ]
    goal_checker_plugins: [ "general_goal_checker" ]
    controller_plugins: [ "FollowPath" ]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0 # if not moving 0.5m in 10s then movement failed

    general_goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: True  # check xy again after rotating to pose

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.75
      max_angular_vel: 0.5
      max_angular_accel: 1.0
      min_approach_linear_velocity: 0.1
      approach_velocity_scaling_dist: 0.3

      use_velocity_scaled_lookahead_dist: True
      min_lookahead_dist: 0.5
      max_lookahead_dist: 1.7
      lookahead_time: 1.0

      use_rotate_to_heading: True
      rotate_to_heading_angular_vel: 1.0

asv/local_costmap:
  local_costmap:
    ros__parameters:
      global_frame: asv/odom
      robot_base_frame: asv/base_link
      robot_radius: 0.65
      height: 3
      width: 3
      resolution: 0.01
      footprint: "[[0.325, 0.425], [0.325, -0.425], [-0.325, -0.425], [-0.325, 0.425]]"
      publish_frequency: 5.0
      update_frequency: 5.0
      use_sim_time: False
      rolling_window: True

asv/global_costmap:
  global_costmap:
    ros__parameters:
      global_frame: map
      robot_base_frame: asv/base_link
      robot_radius: 0.65
      resolution: 0.01
      update_frequency: 5.0
      publish_frequency: 5.0
      track_unknown_space: False
      use_sim_time: False
      rolling_window: False

      plugins: ["static_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: True
        footprint_clearing_enabled: True
        restore_cleared_footprint: True
        map_subscribe_transient_local: True
        transform_tolerance: 0.0
        map_topic: /asv/map
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.9
        cost_scaling_factor: 3.0
      always_send_full_costmap: True
      service_introspection_mode: "disabled"

asv/map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "dog_pool.yaml"
    frame_id: "map"
    topic_name: "map"

asv/planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5

asv/behavior_server:
  ros__parameters:
    local_costmap_topic: local_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_costmap_topic: global_costmap/costmap_raw
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait", "assisted_teleop"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    assisted_teleop:
      plugin: "nav2_behaviors::AssistedTeleop"
    local_frame: asv/odom
    global_frame: map
    robot_base_frame: asv/base_link
    transform_timeout: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 0.5
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2
    enable_stamped_cmd_vel: False
